# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class C3l < Formula
  desc "Use your clipboard to interact with Ollama."
  homepage "https://github.com/FalconTube/c3l"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FalconTube/c3l/releases/download/v0.4.1/c3l_Darwin_x86_64.tar.gz"
      sha256 "e0ad6bd55435a2698054eb6b1f56eb43bb995bc7de1053c1fc1f3b9bcc29e804"

      def install
        bin.install "c3l"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FalconTube/c3l/releases/download/v0.4.1/c3l_Darwin_arm64.tar.gz"
      sha256 "8c6aa7e25fc9df3d79811e4457f9054d495321255b0f27f1a3b696a7062c446c"

      def install
        bin.install "c3l"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/FalconTube/c3l/releases/download/v0.4.1/c3l_Linux_x86_64.tar.gz"
      sha256 "ebb633c252316de03a00b14ea9b7c3f9c50b0ed24d1fed47fe7b9778c560a532"
      def install
        bin.install "c3l"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/FalconTube/c3l/releases/download/v0.4.1/c3l_Linux_armv6.tar.gz"
      sha256 "713e7227dfb48c7d55047c70c8a309fea097262f08979753f97994598f6e9ba0"
      def install
        bin.install "c3l"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/FalconTube/c3l/releases/download/v0.4.1/c3l_Linux_arm64.tar.gz"
      sha256 "59e186b33cf026f3892cd51bccba96459fed472ad8bc0506b3f678011d43f0fa"
      def install
        bin.install "c3l"
      end
    end
  end

  def caveats
    <<~EOS
      Copy any text to the clipboard and use c3l do <prompt> to use the clipboard content.
    EOS
  end

  test do
    system "#{bin}/c3l --version"
  end
end
